services:
  api:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - .:/workdir/fswepp2
    working_dir: /workdir/fswepp2 
    tmpfs:
      - /dev/shm:size=1g
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port 8090
        --reload
        --reload-dir /workdir/fswepp2

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
    environment:
      - PORT=5173
    command: ["bun", "run", "dev"]
    depends_on:
      - api

  caddy:
    image: caddy:latest
    ports:
      - "8091:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - api
      - ui
