services:
  fswepp2:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - .:/workdir/fswepp2
    working_dir: /workdir/fswepp2 
    tmpfs:
      - /ramdisk:size=1g
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port 8090
        --reload
        --reload-dir /workdir/fswepp2

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: builder        # node:20-alpine stage
    working_dir: /app
    ports:
      - "3091:5173"          # external 3091 → Vite 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0         # Vite listens on all interfaces
      - PORT=5173
      - CHOKIDAR_USEPOLLING=true  # reliable file-watching in Docker
    command: npm run dev -- --host 0.0.0.0 --port 5173

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.frontend   # final nginx stage serves /dist
    ports:
      - "8091:80"
