services:
  fswepp2:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - .:/workdir/fswepp2
    working_dir: /workdir/fswepp2 
    tmpfs:
      - /ramdisk:size=1g
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port 8090
        --reload
        --reload-dir /workdir/fswepp2

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: builder
    working_dir: /app
    ports:
      - "3091:5173"
    volumes:
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5173
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.frontend   # final nginx stage serves /dist
    ports:
      - "8091:80"
